name: CML
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: |
          poetry install
      
      - name: Configure Azure and pull data
        run: |
          poetry run dvc remote modify --local azure account_name mnistocr
          poetry run dvc remote modify --local azure account_key ${{ secrets.AZURE_ACCOUNT_KEY }}
          poetry run dvc pull
      
      - name: Run pipeline to train model
        run: |
          poetry run dvc repro
      
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat results.txt >> report.md
          cml send-comment report.md
