name: CML
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: |
          poetry install
      
      - name: Configure Azure and pull data
        run: |
          poetry run dvc remote modify --local azure account_name mnistocr
          poetry run dvc remote modify --local azure account_key ${{ secrets.AZURE_ACCOUNT_KEY }}
          poetry run dvc pull
      
      - name: Run pipeline to train model
        run: |
          poetry run dvc repro
      
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # echo "# CML Report" > report.md
          # echo "## Plots" >> report.md
          # dvc plots diff $PREVIOUS_REF workspace --show-vega --targets evaluation/plots/precision_recall.json > vega.json
          # vl2svg vega.json prc.svg
          # cml publish prc.svg --title "Precision & Recall" --md >> report.md

          # dvc plots diff $PREVIOUS_REF workspace --show-vega --targets evaluation/plots/confusion_matrix.json > vega.json
          # vl2svg vega.json confusion.svg
          # cml publish confusion.svg --title "Confusion Matrix" --md >> report.md

          # echo "## Metrics and Params" >> report.md
          # echo "### $PREVIOUS_REF → workspace" >> report.md
          # dvc exp diff $PREVIOUS_REF --show-md >> report.md

          # cml send-comment report.md
